name             'napalm'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures napalm'
long_description 'Installs/Configures napalm'
version          '0.1.0'
